### ISSUE TITLE
SignatureMeta/upload not working

### ISSUE THREAD

**Issue by maunei** [uc-bd2k/ilincsAPI#1]
Hi,
I am following your tutorial on how to use ilincsAPI.
This uploading is not working, and I think it is something from your side:

# Upload the file # NOT WORKING!

apiUrl<-"http://www.ilincs.org/api/SignatureMeta/upload"
sigFile <- "sigFile.tsv"
req <- POST(apiUrl, body=list(file=upload_file("sigFile.tsv"))) # sigFile.tsv came from signatureData
signatureFile <- httr::content(req)$status$fileName[[1]]
signatureFile
NULL

# Showing, the file for uploading is OK
file.exists("sigFile.tsv")
# [1] TRUE
system(paste("head -3 sigFile.tsv"))
# signatureID	PROBE	ID_geneid	Name_GeneSymbol	Value_LogDiffExp	Significance_pvalue
# LINCSCP_100	NA	16	AARS	1.047	0.200843393802643
# LINCSCP_100	NA	23	ABCF1	0.787095	0.0835145935416222

**Comment by Mario-Medvedovic** [comment]
It was definitely a problem on our side. Thank you for pointing this out to us. The example now works. Please note that the problem has actually been limited to uploading the file with this specific name "sigFile.tsv" and the code would have worked with more or less any other arbitrary file name. I will keep this issue open to test our fix for a bit longer.
Thanks again for the feedback.
Mario
