### ISSUE TITLE
findConcordancesSC error

### ISSUE THREAD

**Issue by Youpla705** [uc-bd2k/ilincsAPI#3]
Hi there, 

Just to point out an issue with findConcordancesSC
![image](https://user-images.githubusercontent.com/38320369/74858605-e222c600-5345-11ea-9f98-ec260c6b69d5.png)

Concentration is not concentration, same for cell line I believe and well time is concentration ;)

Thanks!

**Comment by pilare** [comment]
@Youpla705  thank you for noticing. We are looking into our code to fix this issue.

**Comment by Mario-Medvedovic** [comment]
This problem has been fixed. Thanks again for helping with detecting this problem.
